CREATE DATABASE chat_app

USE chat_app

CREATE TABLE users
(
    id INT PRIMARY KEY IDENTITY(1, 1),
    username VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    hashed_password VARCHAR(MAX) NOT NULL,
    created_at DATETIME DEFAULT GETUTCDATE(),
);

CREATE TABLE rooms
(
    id INT PRIMARY KEY IDENTITY(1, 1),
    name VARCHAR(MAX) NOT NULL,
    is_private BIT NOT NULL DEFAULT 0,
    created_by INT NOT NULL REFERENCES users(id),
    created_at DATETIME NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE messages
(
    id INT PRIMARY KEY IDENTITY(1, 1),
    sender_id INT NOT NULL REFERENCES users(id),
    room_id INT NOT NULL REFERENCES rooms(id),
    content VARCHAR(MAX) NOT NULL,
    created_at DATETIME DEFAULT GETUTCDATE()
);

CREATE TABLE room_members
(
    room_id INT NOT NULL,
    user_id INT NOT NULL,
    joined_at DATETIME DEFAULT GETUTCDATE(),

    CONSTRAINT PK_ROOM_MEMBERS PRIMARY KEY (room_id, user_id),
    CONSTRAINT FK_ROOM_MEMBERS_ROOMS FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE,
    CONSTRAINT FK_ROOM_MEMBERS_USERS FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
